services:
  mongodb:
    image: mongo:latest
    container_name: gameslist_db
    restart: "no"
    volumes:
      - mongo_data:/data/db
    ports:
      - "27019:27017" # Changed from 27017 to avoid port conflicts
    networks:
      - games-net

  api:
    build: ./backend
    container_name: gameslist_api
    restart: "no"
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB_NAME=games_library
    depends_on:
      - mongodb
    networks:
      - games-net

  frontend:
    build: ./frontend
    container_name: gameslist_frontend
    restart: "no"
    ports:
      - "8090:80"
    volumes:
      # Mount the custom nginx config to overwrite the default one in the container
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - games-net

volumes:
  mongo_data:


networks:
  games-net:
    driver: bridge
