version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: gameslist_db
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017" # Exposed for local debugging/migration
    networks:
      - games-net

  api:
    build: ./backend
    container_name: gameslist_api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB_NAME=games_library
    depends_on:
      - mongodb
    networks:
      - games-net

  nginx:
    image: nginx:alpine
    container_name: gameslist_proxy
    restart: unless-stopped
    ports:
      - "8090:80" # Customs Port for the Home Server access
    volumes:
      - ./frontend/dist:/usr/share/nginx/html # Mounts the React Build
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - games-net

volumes:
  mongo_data:


networks:
  games-net:
    driver: bridge
